name = "formosh"
version = "0.7.1"
description = "Type-safe JSON Schema form generator for Gleam/Lustre"
licences = ["MIT"]
repository = { type = "github", user = "radionest", repo = "gleam_formosh" }
links = [
  { title = "Documentation", href = "https://hexdocs.pm/formosh" },
  { title = "GitHub", href = "https://github.com/radionest/gleam_formosh" }
]
target = "javascript"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.3.4 and < 6.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
rsvp = ">= 1.2.0 and < 2.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.9.2 and < 2.0.0"
