name = "file_schema_loader"
version = "1.0.0"
description = "Example of loading JSON schemas from files using Formosh"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.3.5 and < 6.0.0"
lustre_dev_tools = ">= 1.9.2 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
formosh = { path = "../.." }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
